version: '3.8'
services:
  chroma-db:
    image: chromadb/chroma:latest
    container_name: chroma-db
    command: ["--host", "0.0.0.0"]
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
      - ./data/documents:/app/data/documents
volumes:
  chroma_data:
